# Automatically migrated from legacy .beetsconfig.

directory: /Users/dz0004455/Music/Collection
library: /Users/dz0004455/Music/Collection.blb

import:
    write: true
    copy: true
    move: false
    resume: ask
    art: false
    quiet_fallback: skip
    timid: false
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: cover
plugins: web bpd cmus
threaded: true
color: true
timeout: 5.0

paths:
    default: $format/$albumartist/$album/$track $title
    singleton: $format/Singles/$artist/$title
    comp: $format/Compilations/$album/$track $title

bpd:
    port: 6600
    password: password
